WebAppMVC/Models/ErrorViewModel.cs
using System;

namespace WebAppMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

WebAppMVC/Areas/AccountAdministration/Controllers/AccountController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.BusinessLogic.Services.Interfaces;
using WebAppMVC.Controllers;
using WebAppMVC.ViewModels.Requests.AccountAdministration;
using WebAppMVC.ViewModels.Responses.AccountAdministration;

namespace WebAppMVC.Areas.Account.Controllers
{
    [Area("AccountAdministration")]
    public class AccountController: BaseController
    {
        private readonly IAccountService _accountService;

        public AccountController(IAccountService accountService)
        {
            _accountService = accountService;
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateAccountAccountAdministrationRequestViewModel createAccountAccountAdministrationRequestViewModel)
        {
            return await ExecuteAsync(async () =>
            {
                CreateAccountAccountAdministrationResponseViewModel result
                    = await _accountService.CreateAccount(createAccountAccountAdministrationRequestViewModel);

                return RedirectToAction("SignIn", "Account", new { area = "AccountAdministration" });
            },
            createAccountAccountAdministrationRequestViewModel);
        }

        [HttpGet]
        public IActionResult SignIn()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> SignIn(SignInAccountAccountAdministrationRequestViewModel signInAccountAccountAdministrationRequestViewModel)
        {
            return await ExecuteAsync(async () =>
            {
                SignInAccountAccountAdministrationResponseViewModel result
                    = await _accountService.SignIn(signInAccountAccountAdministrationRequestViewModel);

                return RedirectToAction("Index", "Account", new { area = "AccountAdministration" });
            },
            signInAccountAccountAdministrationRequestViewModel);
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return await ExecuteAsync(async () =>
            {
                GetAccountAccountAdministrationResponseViewModel getAccountAccountAdministrationResponseViewModel
                    = await _accountService.GetAccount();

                return View(getAccountAccountAdministrationResponseViewModel);
            });
        }


        [HttpGet]
        public Task<IActionResult> SignOut()
        {
            return ExecuteAsync(() =>
            {
                _accountService.SignOut();
                return Task.FromResult<IActionResult>(RedirectToAction("SignIn", "Account", new { area = "AccountAdministration" }));
            });
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateAccountAccountAdministrationRequestViewModel updateAccountAccountAdministrationRequestViewModel)
        {
            return await ExecuteAsync(async () =>
            {
                await _accountService.UpdateAccount(updateAccountAccountAdministrationRequestViewModel);

                return RedirectToAction("Index", "Account", new { area = "AccountAdministration" });
            },
            updateAccountAccountAdministrationRequestViewModel);
        }


        [HttpGet]
        public async Task<IActionResult> Delete()
        {
            return await ExecuteAsync(async () =>
            {
                await _accountService.DeleteAccount();

                return RedirectToAction("SignIn", "Account", new { area = "AccountAdministration" });
            });
        }

        [HttpGet]
        public IActionResult ChangePassword()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordAccountAccountAdministrationRequestViewModel changePasswordAccountAccountAdministrationRequestViewModel)
        {
            return await ExecuteAsync(async () =>
            {
                await _accountService.ChangePassword(changePasswordAccountAccountAdministrationRequestViewModel);

                return RedirectToAction("Index", "Account", new { area = "AccountAdministration" });
            },
            changePasswordAccountAccountAdministrationRequestViewModel);
        }
    }
}

WebAppMVC/Areas/AuthorManagement/Controllers/AuthorController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.BusinessLogic.Providers.Interfaces;
using WebAppMVC.Controllers;
using WebAppMVC.ViewModels.Responses.AuthorManagement;

namespace WebAppMVC.Areas.AuthorsManagement.Controllers
{
    [Area("AuthorManagement")]
    public class AuthorController: BaseController
    {
        private readonly IAuthorProvider _authorProvider;

        public AuthorController(IAuthorProvider authorProvider)
        {
            _authorProvider = authorProvider;
        }

        [HttpGet]
        public async Task<IActionResult> Get(long id)
        {
            return await ExecuteAsync(async () =>
            {
                GetAuthorAuthorManagementResponseViewModel getAuthorAuthorManagementResponseViewModel
                    = await _authorProvider.Get(id);

                return View(getAuthorAuthorManagementResponseViewModel);
            });
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            return await ExecuteAsync(async () =>
            {
                GetAuthorListAuthorAuthorManagementResponseViewModel getAuthorListAuthorAuthorManagementResponseViewModel
                    = await _authorProvider.GetAuthorList();

                return View(getAuthorListAuthorAuthorManagementResponseViewModel);
            });
        }
    }
}

WebAppMVC/Controllers/BaseController.cs
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.BusinessLogic.Exceptions;

namespace WebAppMVC.Controllers
{
    public class BaseController: Controller
    {
        protected async Task<IActionResult> ExecuteAsync(Func<Task<IActionResult>> method, object model = null)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                IActionResult result = await method?.Invoke();
                return result;
            }
            catch (UnauthorizedException)
            {
                return RedirectToAction("SignIn", "Account", new { area = "AccountAdministration" });
            }
            catch (BadRequestException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
            catch (InternalServerErrorException ex)
            {
                ModelState.AddModelError(string.Empty, ex.Message);
                return View(model);
            }
        }
    }
}

WebAppMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebAppMVC.Models;

namespace WebAppMVC.Controllers
{
    public class HomeController: Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebAppMVC/Areas/AuthorManagement/Views/Author/Get.cshtml
@model GetAuthorAuthorManagementResponseViewModel

@{
    ViewData["Title"] = "Get";
}

<h2>@Model.FirstName @Model.LastName</h2><br />

<h4>Books</h4><br />

<table class="table">
    <tr><th>Title</th><th>Publication Year</th><th>Genres</th></tr>
    @foreach (var book in Model.Books)
    {
        <tr>
            <td>@book.Title</td>
            <td>@book.PublicationYear</td>
            <td>
                <ul>
                    @foreach (var genre in book.Genres)
                    {
                        <li>
                            @genre.Title
                        </li>
                    }
                </ul>
            </td>
        </tr>
    }
</table>

WebAppMVC/Areas/AuthorManagement/Views/Author/Index.cshtml
@model GetAuthorListAuthorAuthorManagementResponseViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Authors</h1>

<table class="table">
    <tr><th>First Name</th><th>Last Name</th><th></th></tr>
    @foreach (var author in Model.AuthorList)
    {
        <tr>
            <td>@author.FirstName</td>
            <td>@author.LastName</td>
            <td>
                <a class="btn btn-info" asp-area="AuthorManagement" asp-controller="Author" asp-action="Get" asp-route-id="@author.Id">Details</a>
            </td>
        </tr>
    }
</table>

WebAppMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

WebAppMVC/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@using WebAppMVC.ViewModels.Responses.AccountAdministration
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppMVC</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @{
                            if (HttpContextAccessor.HttpContext.Request.Cookies.ContainsKey(nameof(SignInAccountAccountAdministrationResponseViewModel.AccessToken)))
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="AccountAdministration" asp-controller="Account" asp-action="Index">My Account</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="AuthorManagement" asp-controller="Author" asp-action="Index">Ukrainian Literature</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="AccountAdministration" asp-controller="Account" asp-action="SignOut">Sign Out</a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="AccountAdministration" asp-controller="Account" asp-action="Create">Sign Up</a>
                                </li>

                                <li class="nav-item">
                                    <a class="nav-link text-dark" asp-area="AccountAdministration" asp-controller="Account" asp-action="SignIn">Sign In</a>
                                </li>
                            }
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - WebAppMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>